using UnityEngine;

//Generated By AI for fast prototyping purposes
namespace CMP.Scripts.Helper
{
    public static class MapTextureGenerator
    {
        public static Texture2D Generate(GridData gridData, MapVisualSettings settings)
        {
            var pixelsPerCell = Mathf.Max(1, settings.pixelsPerCell);

            var texWidth = gridData.Width * pixelsPerCell;
            var texHeight = gridData.Height * pixelsPerCell;

            var tex = new Texture2D(texWidth, texHeight, TextureFormat.RGBA32, false)
            {
                wrapMode = TextureWrapMode.Clamp,
                filterMode = FilterMode.Point
            };

            var pixels = new Color[texWidth * texHeight];
            for (var i = 0; i < pixels.Length; i++)
            {
                pixels[i] = settings.backgroundColor;
            }
            
            tex.SetPixels(pixels);

            for (var y = 0; y < gridData.Height; y++)
            {
                for (var x = 0; x < gridData.Width; x++)
                {
                    switch (gridData.GetCellAt(x, y))
                    {
                        case CellType.Wall:
                            DrawWallCell(tex, gridData, settings, x, y);
                            break;

                        case CellType.AiGate:
                            DrawGateCell(tex, settings, x, y);
                            break;
                    }
                }
            }

            if (settings.drawOuterBorder)
            {
                DrawOuterBorder(tex, settings);
            }

            tex.Apply();
            return tex;
        }

        private static void DrawWallCell(Texture2D tex, GridData data, MapVisualSettings settings, int cellX, int cellY)
        {
            var ppc = settings.pixelsPerCell;
            var baseX = cellX * ppc;
            var baseY = cellY * ppc;

            var upIsWall = IsWall(data, cellX, cellY + 1);
            var downIsWall = IsWall(data, cellX, cellY - 1);
            var leftIsWall = IsWall(data, cellX - 1, cellY);
            var rightIsWall = IsWall(data, cellX + 1, cellY);

            var wallThickness = Mathf.Clamp(settings.wallThickness, 1, ppc);

            if (!upIsWall)
            {
                DrawHorizontal(
                    tex,
                    baseX,
                    baseY + ppc - wallThickness,
                    ppc,
                    wallThickness,
                    settings.wallColor);
            }

            if (!downIsWall)
            {
                DrawHorizontal(
                    tex,
                    baseX,
                    baseY,
                    ppc,
                    wallThickness,
                    settings.wallColor);
            }

            if (!leftIsWall)
            {
                DrawVertical(
                    tex,
                    baseX,
                    baseY,
                    wallThickness,
                    ppc,
                    settings.wallColor);
            }

            if (!rightIsWall)
            {
                DrawVertical(
                    tex,
                    baseX + ppc - wallThickness,
                    baseY,
                    wallThickness,
                    ppc,
                    settings.wallColor);
            }
        }
    
        private static bool IsWall(GridData data, int x, int y)
        {
            if (x < 0 || y < 0 || x >= data.Width || y >= data.Height)
                return false;

            return data.GetCellAt(x, y) == CellType.Wall;
        }

        private static void DrawGateCell(Texture2D tex, MapVisualSettings settings, int cellX, int cellY)
        {
            var ppc = settings.pixelsPerCell;
            var baseX = cellX * ppc;
            var baseY = cellY * ppc;

            var gateThickness = Mathf.Clamp(settings.gateThickness, 1, ppc);
            var midY = baseY + ppc / 2 - gateThickness / 2;

            DrawHorizontal(
                tex,
                baseX,
                midY,
                ppc,
                gateThickness,
                settings.gateColor);
        }

        private static void DrawOuterBorder(Texture2D tex, MapVisualSettings settings)
        {
            var texWidth = tex.width;
            var texHeight = tex.height;
            var thickness = Mathf.Clamp(settings.outerBorderThickness, 1, Mathf.Min(texWidth, texHeight));

            DrawHorizontal(tex, 0, 0, texWidth, thickness, settings.outerBorderColor);
            DrawHorizontal(tex, 0, texHeight - thickness, texWidth, thickness, settings.outerBorderColor);
            DrawVertical(tex, 0, 0, thickness, texHeight, settings.outerBorderColor);
            DrawVertical(tex, texWidth - thickness, 0, thickness, texHeight, settings.outerBorderColor);
        }

        private static void DrawHorizontal(Texture2D tex, int startX, int startY, int length, int thickness, Color c)
        {
            var texWidth = tex.width;
            var texHeight = tex.height;

            for (var y = 0; y < thickness; y++)
            {
                var py = startY + y;
                if (py < 0 || py >= texHeight) continue;

                for (var x = 0; x < length; x++)
                {
                    var px = startX + x;
                    if (px < 0 || px >= texWidth) continue;

                    tex.SetPixel(px, py, c);
                }
            }
        }

        private static void DrawVertical(Texture2D tex, int startX, int startY, int thickness, int length, Color c)
        {
            var texWidth = tex.width;
            var texHeight = tex.height;

            for (var x = 0; x < thickness; x++)
            {
                var px = startX + x;
                if (px < 0 || px >= texWidth) continue;

                for (var y = 0; y < length; y++)
                {
                    var py = startY + y;
                    if (py < 0 || py >= texHeight) continue;

                    tex.SetPixel(px, py, c);
                }
            }
        }

    }
}
